Name: Cake.MkDocs
Nuget: Cake.MkDocs
Assemblies:
- "/**/Cake.MkDocs.dll"
Repository: https://github.com/michalkowal/Cake.MkDocs
Author: michalkowal
Description: "Cake MkDocs AddIn."
Categories:
- Cake,
- Script,
- Build,
- MkDocs
